name: repository events
on: [push, pull_request, issues]

jobs: 
  checkout-test :
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_WORKFLOW
          echo $GITHUB_ACTION
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_SERVER_URL
          echo $GITHUB_API_URL
          echo $GITHUB_GRAPHQL_URL
          echo $GITHUB_ENV
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo $GITHUB_JOB
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTION_REPOSITORY
          echo $GITHUB_ACTION_REF
          echo $GITHUB_PATH
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - uses: actions/checkout@v3